const products = [
  {
    name: "Sơ Mi Oxford Nam",
    description:
      "Sơ mi nam dáng thoải mái, làm từ cotton thoáng mát, phù hợp đi làm hoặc dạo phố. Có cổ bẻ, tay dài và hàng nút phía trước, dễ phối đồ.",
    price: 650000,
    discountPrice: 550000,
    countInStock: 20,
    sku: "OX-SH-001",
    category: "Phần Trên",
    brand: "Việt Tiến",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Xanh Dương", "Xám"],
    collections: "Công Sở",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=1",
        altText: "Sơ Mi Oxford Nam Mặt Trước",
      },
      {
        url: "https://picsum.photos/500/500?random=2",
        altText: "Sơ Mi Oxford Nam Mặt Sau",
      },
    ],
    rating: 4.5,
    numReviews: 12,
  },
  {
    name: "Sơ Mi Nam Ôm Dáng",
    description:
      "Sơ mi nam ôm dáng, vải cotton pha co giãn, thoải mái cho công việc hoặc tiệc tối. Có cổ đứng và tay áo nút điều chỉnh.",
    price: 500000,
    discountPrice: 420000,
    countInStock: 35,
    sku: "SLIM-SH-002",
    category: "Phần Trên",
    brand: "NEM",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Đen", "Xanh Đậm", "Trắng"],
    collections: "Trang Trọng",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=3",
        altText: "Sơ Mi Nam Ôm Dáng Mặt Trước",
      },
      {
        url: "https://picsum.photos/500/500?random=4",
        altText: "Sơ Mi Nam Ôm Dáng Mặt Sau",
      },
    ],
    rating: 4.8,
    numReviews: 15,
  },
  {
    name: "Sơ Mi Denim Nam",
    description:
      "Sơ mi denim nam dáng vừa, làm từ vải denim nhẹ, thích hợp mặc hàng ngày hoặc phối lớp. Có nút bấm và viền thẳng đơn giản.",
    price: 750000,
    discountPrice: 650000,
    countInStock: 15,
    sku: "CAS-DEN-003",
    category: "Phần Trên",
    brand: "K&K Fashion",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xanh Nhạt", "Xanh Đậm"],
    collections: "Dạo Phố",
    material: "Vải denim",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=5",
        altText: "Sơ Mi Denim Nam Mặt Trước",
      },
      {
        url: "https://picsum.photos/500/500?random=6",
        altText: "Sơ Mi Denim Nam Mặt Sau",
      },
    ],
    rating: 4.6,
    numReviews: 8,
  },
  {
    name: "Sơ Mi Họa Tiết Biển",
    description:
      "Sơ mi nam họa tiết biển, dáng rộng, tay ngắn, thoáng mát cho mùa hè. Phù hợp đi du lịch hoặc dạo chơi cuối tuần.",
    price: 450000,
    discountPrice: 380000,
    countInStock: 25,
    sku: "PRNT-RES-004",
    category: "Phần Trên",
    brand: "Coolmate",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xanh Lá"],
    collections: "Du Lịch",
    material: "Vải lụa",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=7",
        altText: "Sơ Mi Họa Tiết Biển Mặt Trước",
      },
      {
        url: "https://picsum.photos/500/500?random=8",
        altText: "Sơ Mi Họa Tiết Biển Mặt Sau",
      },
    ],
    rating: 4.4,
    numReviews: 10,
  },
  {
    name: "Sơ Mi Nam Dễ Là",
    description:
      "Sơ mi nam dáng ôm, vải cotton dễ là, phù hợp đi làm hoặc gặp gỡ bạn bè. Có cổ đứng, tay dài và viền cong nhẹ.",
    price: 550000,
    discountPrice: 480000,
    countInStock: 30,
    sku: "SLIM-EIR-005",
    category: "Phần Trên",
    brand: "Canifa",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Xám Nhạt"],
    collections: "Công Sở",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=9",
        altText: "Sơ Mi Nam Dễ Là Mặt Trước",
      },
      {
        url: "https://picsum.photos/500/500?random=10",
        altText: "Sơ Mi Nam Dễ Là Mặt Sau",
      },
    ],
    rating: 5,
    numReviews: 14,
  },
  {
    name: "Áo Polo Nam Cổ Gân",
    description:
      "Áo polo nam cổ gân, làm từ cotton thoáng mát, dáng ôm vừa vặn. Thích hợp mặc đi làm, đi chơi hoặc ở nhà.",
    price: 400000,
    discountPrice: 340000,
    countInStock: 50,
    sku: "POLO-TSH-006",
    category: "Phần Trên",
    brand: "Việt Tiến",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Xanh Đậm", "Đỏ"],
    collections: "Dạo Phố",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=11",
        altText: "Áo Polo Nam Cổ Gân Mặt Trước",
      },
      {
        url: "https://picsum.photos/500/500?random=12",
        altText: "Áo Polo Nam Cổ Gân Mặt Sau",
      },
    ],
    rating: 4.3,
    numReviews: 22,
  },
  {
    name: "Áo Thun Nam Oversized",
    description:
      "Áo thun nam oversized in họa tiết cá tính, dáng rộng, thích hợp phối với quần jeans hoặc jogger cho phong cách đường phố.",
    price: 350000,
    discountPrice: 290000,
    countInStock: 40,
    sku: "OVS-GRF-007",
    category: "Phần Trên",
    brand: "NEM",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Đen", "Xám Đậm"],
    collections: "Đường Phố",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=13",
        altText: "Áo Thun Nam Oversized Mặt Trước",
      },
      {
        url: "https://picsum.photos/500/500?random=14",
        altText: "Áo Thun Nam Oversized Mặt Sau",
      },
    ],
    rating: 4.6,
    numReviews: 30,
  },
  {
    name: "Áo Henley Nam Dáng Vừa",
    description:
      "Áo Henley nam dáng vừa, vải cotton pha co giãn, có hàng nút phía trước. Phù hợp mặc hàng ngày hoặc phối đồ năng động.",
    price: 380000,
    discountPrice: 320000,
    countInStock: 35,
    sku: "REG-HEN-008",
    category: "Phần Trên",
    brand: "K&K Fashion",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xám Nhạt", "Xanh Ô Liu", "Đen"],
    collections: "Dạo Phố",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=15",
        altText: "Áo Henley Nam Dáng Vừa Mặt Trước",
      },
      {
        url: "https://picsum.photos/500/500?random=16",
        altText: "Áo Henley Nam Dáng Vừa Mặt Sau",
      },
    ],
    rating: 4.5,
    numReviews: 25,
  },
  {
    name: "Áo Thun Nam Dài Tay",
    description:
      "Áo thun dài tay nam vải cotton mềm, thoáng mát, dáng ôm vừa vặn. Thích hợp mặc lớp hoặc mặc riêng trong thời tiết se lạnh.",
    price: 450000,
    discountPrice: 380000,
    countInStock: 20,
    sku: "LST-THR-009",
    category: "Phần Trên",
    brand: "Coolmate",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xám Đậm", "Xanh Lục", "Xanh Đậm"],
    collections: "Mùa Đông",
    material: "Len",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=17",
        altText: "Áo Thun Nam Dài Tay Mặt Trước",
      },
    ],
    rating: 4.4,
    numReviews: 18,
  },
  {
    name: "Áo Thun Nam Cổ V",
    description:
      "Áo thun nam cổ V dáng vừa, vải cotton thoáng mát, thiết kế đơn giản. Phù hợp mặc hàng ngày hoặc đi chơi thoải mái.",
    price: 250000,
    discountPrice: 200000,
    countInStock: 60,
    sku: "VNECK-CLS-010",
    category: "Phần Trên",
    brand: "Canifa",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Đen", "Xanh Đậm"],
    collections: "Cơ Bản",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=18",
        altText: "Áo Thun Nam Cổ V Mặt Trước",
      },
    ],
    rating: 4.7,
    numReviews: 28,
  },
  {
    name: "Quần Jogger Nam Ôm Dáng",
    description:
      "Quần jogger nam dáng ôm, có dây rút và gấu bo, vải cotton pha mềm mại. Phù hợp tập gym hoặc đi chơi năng động.",
    price: 650000,
    discountPrice: 550000,
    countInStock: 20,
    sku: "BW-001",
    category: "Phần Dưới",
    brand: "Việt Tiến",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Đen", "Xám", "Xanh Đậm"],
    collections: "Năng Động",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=19",
        altText: "Quần Jogger Nam Ôm Dáng Mặt Trước",
      },
    ],
    rating: 4.5,
    numReviews: 12,
  },
  {
    name: "Quần Cargo Nam",
    description:
      "Quần cargo nam dáng rộng, có nhiều túi tiện dụng và dây rút. Phù hợp cho phong cách dạo phố hoặc hoạt động ngoài trời.",
    price: 750000,
    discountPrice: 650000,
    countInStock: 15,
    sku: "BW-002",
    category: "Phần Dưới",
    brand: "NEM",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xanh Ô Liu", "Đen"],
    collections: "Đường Phố",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=20",
        altText: "Quần Cargo Nam Mặt Trước",
      },
    ],
    rating: 4.7,
    numReviews: 20,
  },
  {
    name: "Quần Thể Thao Nam",
    description:
      "Quần thể thao nam dáng thuôn, có dây rút và thắt lưng co giãn. Thích hợp mặc ở nhà hoặc tập luyện thể thao.",
    price: 550000,
    discountPrice: 480000,
    countInStock: 25,
    sku: "BW-003",
    category: "Phần Dưới",
    brand: "K&K Fashion",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xám", "Đen", "Xanh Dương"],
    collections: "Thư Giãn",
    material: "Vải nỉ",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=21",
        altText: "Quần Thể Thao Nam Mặt Trước",
      },
    ],
    rating: 4.3,
    numReviews: 18,
  },
  {
    name: "Quần Jeans Nam",
    description:
      "Quần jeans nam dáng ôm, vải denim co giãn nhẹ, có khóa kéo và 5 túi. Phù hợp mặc hàng ngày hoặc đi chơi.",
    price: 900000,
    discountPrice: 780000,
    countInStock: 30,
    sku: "BW-004",
    category: "Phần Dưới",
    brand: "Coolmate",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xanh Đậm", "Xanh Nhạt"],
    collections: "Denim",
    material: "Vải denim",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=22",
        altText: "Quần Jeans Nam Mặt Trước",
      },
    ],
    rating: 4.6,
    numReviews: 22,
  },
  {
    name: "Quần Chino Nam",
    description:
      "Quần chino nam dáng ôm, vải cotton co giãn, có nút đóng và túi trước, sau. Phù hợp mặc đi làm hoặc dạo phố.",
    price: 850000,
    discountPrice: 720000,
    countInStock: 40,
    sku: "BW-005",
    category: "Phần Dưới",
    brand: "Canifa",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Be", "Xanh Đậm", "Đen"],
    collections: "Công Sở",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=23",
        altText: "Quần Chino Nam Mặt Trước",
      },
    ],
    rating: 4.8,
    numReviews: 15,
  },
  {
    name: "Quần Thể Thao Sọc",
    description:
      "Quần thể thao nam dáng thuôn, có sọc bên hông, thắt lưng co giãn. Phù hợp tập gym hoặc mặc năng động hàng ngày.",
    price: 650000,
    discountPrice: 550000,
    countInStock: 20,
    sku: "BW-006",
    category: "Phần Dưới",
    brand: "Việt Tiến",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Đen", "Đỏ", "Xanh Dương"],
    collections: "Năng Động",
    material: "Vải nỉ",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=24",
        altText: "Quần Thể Thao Sọc Mặt Trước",
      },
    ],
    rating: 4.2,
    numReviews: 17,
  },
  {
    name: "Quần Tây Nam Ôm Dáng",
    description:
      "Quần quần tây nam dáng ôm, có đỉa thắt lưng và khóa móc. Phù hợp mặc đi làm hoặc các dịp trang trọng.",
    price: 950000,
    discountPrice: 820000,
    countInStock: 15,
    sku: "BW-007",
    category: "Phần Dưới",
    brand: "NEM",
    sizes: ["M", "L", "XL"],
    colors: ["Xám", "Đen"],
    collections: "Công Sở",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=25",
        altText: "Quần Tây Nam Ôm Dáng Mặt Trước",
      },
    ],
    rating: 4.7,
    numReviews: 10,
  },
  {
    name: "Quần Cargo Nam Dáng Rộng",
    description:
      "Quần cargo nam dáng rộng, có nhiều túi tiện dụng và dây rút. Phù hợp dạo phố hoặc hoạt động ngoài trời.",
    price: 800000,
    discountPrice: 700000,
    countInStock: 25,
    sku: "BW-008",
    category: "Phần Dưới",
    brand: "K&K Fashion",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xanh Ô Liu", "Nâu", "Đen"],
    collections: "Đường Phố",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=26",
        altText: "Quần Cargo Nam Dáng Rộng Mặt Trước",
      },
    ],
    rating: 4.5,
    numReviews: 13,
  },
  {
    name: "Quần Thể Thao Nam Dáng Rộng",
    description:
      "Quần thể thao nam dáng rộng, vải fleece mềm mại, có dây rút. Thích hợp mặc ở nhà hoặc đi chơi thoải mái.",
    price: 550000,
    discountPrice: 480000,
    countInStock: 35,
    sku: "BW-009",
    category: "Phần Dưới",
    brand: "Coolmate",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xám", "Đen", "Xanh Đậm"],
    collections: "Thư Giãn",
    material: "Vải nỉ",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=27",
        altText: "Quần Thể Thao Nam Dáng Rộng Mặt Trước",
      },
    ],
    rating: 4.3,
    numReviews: 14,
  },
  {
    name: "Quần Tây Nam Trang Trọng",
    description:
      "Quần tây nam dáng ôm, vải chống nhăn nhẹ, mang lại vẻ lịch sự cho công sở hoặc sự kiện trang trọng.",
    price: 1100000,
    discountPrice: 950000,
    countInStock: 20,
    sku: "BW-010",
    category: "Phần Dưới",
    brand: "Canifa",
    sizes: ["M", "L", "XL"],
    colors: ["Đen", "Xanh Đậm"],
    collections: "Trang Trọng",
    material: "Vải cotton",
    gender: "Nam",
    images: [
      {
        url: "https://picsum.photos/500/500?random=28",
        altText: "Quần Tây Nam Trang Trọng Mặt Trước",
      },
    ],
    rating: 4.9,
    numReviews: 8,
  },
  {
    name: "Quần Jeans Nữ Lưng Cao",
    description:
      "Quần jeans nữ lưng cao, vải denim co giãn, dáng ôm sát tôn dáng. Phù hợp mặc đi chơi hoặc dạo phố.",
    price: 750000,
    discountPrice: 650000,
    countInStock: 30,
    sku: "BW-W-001",
    category: "Phần Dưới",
    brand: "Việt Tiến",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Xanh Đậm", "Đen", "Xanh Nhạt"],
    collections: "Denim",
    material: "Vải denim",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=29",
        altText: "Quần Jeans Nữ Lưng Cao Mặt Trước",
      },
    ],
    rating: 4.8,
    numReviews: 20,
  },
  {
    name: "Quần Tây Nữ Ống Rộng",
    description:
      "Quần tây nữ ống rộng lưng cao, có túi bên, mang lại vẻ thanh lịch và thoải mái cho công sở hoặc dạo phố.",
    price: 900000,
    discountPrice: 780000,
    countInStock: 25,
    sku: "BW-W-002",
    category: "Phần Dưới",
    brand: "NEM",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Be", "Đen", "Trắng"],
    collections: "Trang Trọng",
    material: "Vải cotton",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=30",
        altText: "Quần Tây Nữ Ống Rộng Mặt Trước",
      },
    ],
    rating: 4.7,
    numReviews: 15,
  },
  {
    name: "Quần Legging Nữ",
    description:
      "Quần legging nữ lưng cao, vải co giãn mềm mại, ôm sát tôn dáng. Thích hợp mặc ở nhà, tập gym hoặc đi chơi.",
    price: 400000,
    discountPrice: 340000,
    countInStock: 40,
    sku: "BW-W-003",
    category: "Phần Dưới",
    brand: "K&K Fashion",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Đen", "Xám", "Xanh Đậm"],
    collections: "Năng Động",
    material: "Vải cotton",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=31",
        altText: "Quần Legging Nữ Mặt Trước",
      },
    ],
    rating: 4.5,
    numReviews: 30,
  },
  {
    name: "Váy Midi Xếp Ly",
    description:
      "Váy midi xếp ly lưng cao, vải mềm rũ đẹp, phù hợp mặc đi làm hoặc đi tiệc nhẹ. Dễ phối với áo thun hoặc sơ mi.",
    price: 850000,
    discountPrice: 720000,
    countInStock: 20,
    sku: "BW-W-004",
    category: "Phần Dưới",
    brand: "Coolmate",
    sizes: ["S", "M", "L"],
    colors: ["Hồng Phấn", "Xanh Đậm", "Đen"],
    collections: "Mùa Xuân",
    material: "Vải lụa",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=32",
        altText: "Váy Midi Xếp Ly Mặt Trước",
      },
    ],
    rating: 4.6,
    numReviews: 18,
  },
  {
    name: "Quần Palazzo Nữ",
    description:
      "Quần palazzo nữ lưng cao, dáng rộng rũ, thoáng mát. Phù hợp đi biển, dạo phố hoặc mặc hè thoải mái.",
    price: 700000,
    discountPrice: 600000,
    countInStock: 35,
    sku: "BW-W-005",
    category: "Phần Dưới",
    brand: "Canifa",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Be", "Xanh Nhạt"],
    collections: "Mùa Hè",
    material: "Vải lanh",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=33",
        altText: "Quần Palazzo Nữ Mặt Trước",
      },
    ],
    rating: 4.4,
    numReviews: 22,
  },
  {
    name: "Quần Jogger Nữ Lưng Cao",
    description:
      "Quần jogger nữ lưng cao, có dây rút, vải cotton pha mềm. Thích hợp mặc ở nhà, tập gym hoặc đi chơi nhẹ.",
    price: 650000,
    discountPrice: 550000,
    countInStock: 30,
    sku: "BW-W-006",
    category: "Phần Dưới",
    brand: "Việt Tiến",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Đen", "Xám", "Hồng Phấn"],
    collections: "Thư Giãn",
    material: "Vải cotton",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=34",
        altText: "Quần Jogger Nữ Lưng Cao Mặt Trước",
      },
    ],
    rating: 4.3,
    numReviews: 25,
  },
  {
    name: "Quần Short Nữ Lưng Thắt",
    description:
      "Quần short nữ lưng thắt thời trang, ống rộng, thoáng mát. Phù hợp mặc đi chơi hoặc dạo phố mùa hè.",
    price: 550000,
    discountPrice: 480000,
    countInStock: 20,
    sku: "BW-W-007",
    category: "Phần Dưới",
    brand: "NEM",
    sizes: ["S", "M", "L"],
    colors: ["Trắng", "Kaki", "Xanh Dương"],
    collections: "Mùa Hè",
    material: "Vải lanh",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=35",
        altText: "Quần Short Nữ Lưng Thắt Mặt Trước",
      },
    ],
    rating: 4.5,
    numReviews: 19,
  },
  {
    name: "Quần Short Denim Nữ",
    description:
      "Quần short denim nữ lưng cao, vải co giãn, viền gấu thô. Thích hợp phối áo thun hoặc croptop cho mùa hè.",
    price: 650000,
    discountPrice: 550000,
    countInStock: 25,
    sku: "BW-W-008",
    category: "Phần Dưới",
    brand: "K&K Fashion",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xanh Dương", "Đen", "Trắng"],
    collections: "Denim",
    material: "Vải denim",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=36",
        altText: "Quần Short Denim Nữ Mặt Trước",
      },
    ],
    rating: 4.7,
    numReviews: 15,
  },
  {
    name: "Quần Culottes Nữ",
    description:
      "Quần culottes nữ lưng cao, ống rộng, dáng ngắn. Thoải mái và thời trang, phù hợp mặc đi chơi hoặc đi làm nhẹ.",
    price: 750000,
    discountPrice: 650000,
    countInStock: 30,
    sku: "BW-W-009",
    category: "Phần Dưới",
    brand: "Coolmate",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Đen", "Trắng", "Xanh Ô Liu"],
    collections: "Dạo Phố",
    material: "Vải lanh",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=37",
        altText: "Quần Culottes Nữ Mặt Trước",
      },
    ],
    rating: 4.6,
    numReviews: 23,
  },
  {
    name: "Quần Tây Nữ Xếp Ly",
    description:
      "Quần tây nữ xếp ly dáng ôm, thanh lịch. Phù hợp mặc đi làm hoặc các dịp trang trọng, dễ phối với sơ mi.",
    price: 1100000,
    discountPrice: 950000,
    countInStock: 25,
    sku: "BW-W-010",
    category: "Phần Dưới",
    brand: "Canifa",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xanh Đậm", "Đen", "Xám"],
    collections: "Trang Trọng",
    material: "Vải cotton",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=38",
        altText: "Quần Tây Nữ Xếp Ly Mặt Trước",
      },
    ],
    rating: 4.8,
    numReviews: 20,
  },
  {
    name: "Áo Crop Nữ Đan Len",
    description:
      "Áo crop nữ đan len dáng ôm, thời trang và trẻ trung. Phù hợp phối với quần lưng cao hoặc váy cho phong cách dạo phố.",
    price: 600000,
    discountPrice: 520000,
    countInStock: 25,
    sku: "TW-W-001",
    category: "Phần Trên",
    brand: "Việt Tiến",
    sizes: ["S", "M", "L"],
    colors: ["Be", "Trắng"],
    collections: "Đan Len",
    material: "Len",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=39",
        altText: "Áo Crop Nữ Đan Len Mặt Trước",
      },
    ],
    rating: 4.6,
    numReviews: 15,
  },
  {
    name: "Áo Sơ Mi Nữ Hoa Boho",
    description:
      "Áo sơ mi nữ họa tiết hoa boho, dáng rộng, tay phồng. Thoáng mát, phù hợp mặc đi chơi hoặc dạo phố mùa hè.",
    price: 750000,
    discountPrice: 650000,
    countInStock: 30,
    sku: "TW-W-002",
    category: "Phần Trên",
    brand: "NEM",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Hồng Phấn"],
    collections: "Mùa Hè",
    material: "Vải lụa",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=40",
        altText: "Áo Sơ Mi Nữ Hoa Boho Mặt Trước",
      },
    ],
    rating: 4.7,
    numReviews: 20,
  },
  {
    name: "Áo Thun Nữ Cổ Tròn",
    description:
      "Áo thun nữ cổ tròn dáng vừa, vải cotton mềm mại. Phù hợp mặc hàng ngày, đi học hoặc đi chơi thoải mái.",
    price: 400000,
    discountPrice: 340000,
    countInStock: 50,
    sku: "TW-W-003",
    category: "Phần Trên",
    brand: "K&K Fashion",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Đen", "Trắng", "Xám"],
    collections: "Cơ Bản",
    material: "Vải cotton",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=41",
        altText: "Áo Thun Nữ Cổ Tròn Mặt Trước",
      },
    ],
    rating: 4.5,
    numReviews: 25,
  },
  {
    name: "Áo Trễ Vai Nữ",
    description:
      "Áo trễ vai nữ thời trang, có tay bèo nhún. Phù hợp mặc đi tiệc hoặc dạo phố, mang lại vẻ nữ tính, cuốn hút.",
    price: 700000,
    discountPrice: 600000,
    countInStock: 35,
    sku: "TW-W-004",
    category: "Phần Trên",
    brand: "Coolmate",
    sizes: ["S", "M", "L"],
    colors: ["Đỏ", "Trắng", "Xanh Dương"],
    collections: "Tiệc Tối",
    material: "Vải lụa",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=42",
        altText: "Áo Trễ Vai Nữ Mặt Trước",
      },
    ],
    rating: 4.7,
    numReviews: 18,
  },
  {
    name: "Áo Hai Dây Nữ Viền Ren",
    description:
      "Áo hai dây nữ viền ren, vải lụa nhẹ, có dây đai điều chỉnh. Phù hợp mặc mùa hè hoặc phối lớp với áo khoác.",
    price: 550000,
    discountPrice: 480000,
    countInStock: 40,
    sku: "TW-W-005",
    category: "Phần Trên",
    brand: "Canifa",
    sizes: ["S", "M", "L"],
    colors: ["Đen", "Trắng"],
    collections: "Mùa Hè",
    material: "Vải lụa",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=43",
        altText: "Áo Hai Dây Nữ Viền Ren Mặt Trước",
      },
    ],
    rating: 4.8,
    numReviews: 22,
  },
  {
    name: "Áo Thun Nữ In Họa Tiết",
    description:
      "Áo thun nữ in họa tiết cá tính, dáng rộng. Phù hợp phối với quần jeans hoặc váy cho phong cách dạo phố trẻ trung.",
    price: 450000,
    discountPrice: 380000,
    countInStock: 45,
    sku: "TW-W-006",
    category: "Phần Trên",
    brand: "Việt Tiến",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Đen"],
    collections: "Đường Phố",
    material: "Vải cotton",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=44",
        altText: "Áo Thun Nữ In Họa Tiết Mặt Trước",
      },
    ],
    rating: 4.6,
    numReviews: 30,
  },
  {
    name: "Áo Dài Tay Nữ Gân",
    description:
      "Áo dài tay nữ gân, vải cotton pha mềm mại, dáng ôm. Phù hợp mặc lớp hoặc mặc riêng trong mùa thu mát mẻ.",
    price: 850000,
    discountPrice: 720000,
    countInStock: 30,
    sku: "TW-W-007",
    category: "Phần Trên",
    brand: "NEM",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Xám", "Hồng Phấn", "Nâu Nhạt"],
    collections: "Mùa Thu",
    material: "Len",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=45",
        altText: "Áo Dài Tay Nữ Gân Mặt Trước",
      },
    ],
    rating: 4.7,
    numReviews: 26,
  },
  {
    name: "Áo Sơ Mi Nữ Tay Bèo",
    description:
      "Áo sơ mi nữ tay bèo, vải nhẹ, dáng ôm nhẹ. Phù hợp mặc đi chơi hoặc đi làm, mang lại vẻ nữ tính, thanh lịch.",
    price: 700000,
    discountPrice: 600000,
    countInStock: 20,
    sku: "TW-W-008",
    category: "Phần Trên",
    brand: "K&K Fashion",
    sizes: ["S", "M", "L"],
    colors: ["Trắng", "Xanh Xanh Đậm", "Hồng Phấn"],
    collections: "Mùa Hè",
    material: "Vải lụa",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=46",
        altText: "Áo Sơ Mi Nữ Tay Bèo Mặt Trước",
      },
    ],
    rating: 4.5,
    numReviews: 19,
  },
  {
    name: "Sơ Mi Nữ Cài Nút",
    description:
      "Sơ mi nữ cài nút dáng ôm, vải cotton mềm, phù hợp mặc đi làm hoặc đi chơi. Dễ phối với quần tây hoặc jeans.",
    price: 900000,
    discountPrice: 780000,
    countInStock: 25,
    sku: "TW-W-009",
    category: "Phần Trên",
    brand: "Coolmate",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Xanh Nhạt", "Đen"],
    collections: "Công Sở",
    material: "Vải cotton",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=47",
        altText: "Sơ Mi Nữ Cài Nút Mặt Trước",
      },
    ],
    rating: 4.8,
    numReviews: 25,
  },
  {
    name: "Áo Cổ V Nữ Quấn Eo",
    description:
      "Áo cổ V nữ quấn eo, có thắt lưng buộc, dáng thanh lịch. Phù hợp mặc đi chơi hoặc tiệc nhẹ, tôn dáng cuốn hút.",
    price: 750000,
    discountPrice: 650000,
    countInStock: 30,
    sku: "TW-W-010",
    category: "Phần Trên",
    brand: "Canifa",
    sizes: ["S", "M", "L"],
    colors: ["Đỏ", "Đen", "Trắng"],
    collections: "Tiệc Tối",
    material: "Vải lụa",
    gender: "Nữ",
    images: [
      {
        url: "https://picsum.photos/500/500?random=48",
        altText: "Áo Cổ V Nữ Quấn Eo Mặt Trước",
      },
    ],
    rating: 4.7,
    numReviews: 22,
  },
];

module.exports = products;
